In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('/kaggle/input/final-dataset/finalDF (1).csv')
df.head()

,Concepts,Type_relation,Concept_of_type_relation,Definition,Synonym,Reference,Process_name,Figure
0,plan risk management,studies,project risk,define the plan risk management concept. risk ...,NaN,"described in section 13.1.3.1,described in sec...",plan identify ambiguity,NaN
1,plan risk management,studies,project risk,define the plan risk management concept. the r...,NaN,"described in section 11.2.3.2,described in sec...",plan identify ambiguity,NaN
2,plan risk management inputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN
3,plan risk management tools and techniques,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN
4,plan risk management outputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN

In [5]:
!pip install networkx plotly rdflib

Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (3.3)
Requirement already satisfied: plotly in /opt/conda/lib/python3.10/site-packages (5.22.0)
Collecting rdflib
  Downloading rdflib-7.1.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: tenacity>=6.2.0 in /opt/conda/lib/python3.10/site-packages (from plotly) (8.3.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from plotly) (21.3)
Collecting isodate<1.0.0,>=0.7.2 (from rdflib)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pyparsing<4,>=2.1.0 in /opt/conda/lib/python3.10/site-packages (from rdflib) (3.1.2)
Downloading rdflib-7.1.1-py3-none-any.whl (562 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 562.4/562.4 kB 8.9 MB/s eta 0:00:00a 0:00:01
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Installing collected packages: isodate, rdflib
Successfully installed isodate-0.7.2 rdflib-7.1.1

In [6]:
from rdflib import Graph, URIRef, Literal, Namespace
import pandas as pd
import networkx as nx
import plotly.graph_objs as go


# Initialize an RDF graph
rdf_graph = Graph()
EX = Namespace("")

# Add data to RDF graph
for _, row in df.iterrows():
    subject = URIRef(EX[row['Concepts'].replace(" ", "_")])
    predicate = URIRef(EX[row['Type_relation'].replace(" ", "_")])
    obj = URIRef(EX[row['Concept_of_type_relation'].replace(" ", "_")])
    rdf_graph.add((subject, predicate, obj))

# Save the graph to a file (optional)

In [7]:
G = nx.DiGraph()
for s, p, o in rdf_graph:
    G.add_edge(str(s), str(o), label=str(p).split('/')[-1])

# 3D Positioning for nodes
pos_3d = nx.spring_layout(G, dim=3, seed=42)

def add_line_breaks(text, words_per_line=5):
    words = text.split()
    lines = [" ".join(words[i:i+words_per_line]) for i in range(0, len(words), words_per_line)]
    return "<br>".join(lines)

# Extract node positions
x_nodes = [pos_3d[node][0] for node in G.nodes()]
y_nodes = [pos_3d[node][1] for node in G.nodes()]
z_nodes = [pos_3d[node][2] for node in G.nodes()]
node_labels = [{"Concepts :"+ str(df.loc[i, "Concepts"] ) 
              +': <br> Definition: '+add_line_breaks(str(df.loc[i, "Definition"] ), words_per_line=10)
              +'<br> Synonym: '+ str(df.loc[i, "Synonym"] )
              + "<br> Process Name: "+ str(df.loc[i, "Process_name"]) }for i in range(len(df))]
edges_labels = list(df.Type_relation)

# Extract edge positions
edge_x = []
edge_y = []
edge_z = []
for edge in G.edges():
    edge_x += [pos_3d[edge[0]][0], pos_3d[edge[1]][0], None]
    edge_y += [pos_3d[edge[0]][1], pos_3d[edge[1]][1], None]
    edge_z += [pos_3d[edge[0]][2], pos_3d[edge[1]][2], None]

# Create Plotly traces
edge_trace = go.Scatter3d(
    x=edge_x, y=edge_y, z=edge_z,
    line=dict(width=6, color='black'),
    hovertext=edges_labels,
    mode='lines',
    hoverinfo="text"
)

node_trace = go.Scatter3d(
    x=x_nodes, y=y_nodes, z=z_nodes,
    mode='markers+text',
    marker=dict(size=10, color='red', opacity=1),
    hovertext=node_labels,
    textposition="middle center",
    hoverinfo="text",
)

# Layout and plot
fig = go.Figure(data=[edge_trace, node_trace])
fig.update_layout(
    scene=dict(
        xaxis=dict(showbackground=False),
        yaxis=dict(showbackground=False),
        zaxis=dict(showbackground=False)
    ),
    title='3D Visualization of RDF Graph',
      showlegend=True,
    hoverlabel=dict(
        bgcolor="white",    # Background color for hover label
        font_size=12,       # Font size
        font_family="Arial", # Font family
        bordercolor="black"  # Border color around the hover label
    )
)

fig.show()

In [8]:
!pip install node2vec

Collecting node2vec
  Downloading node2vec-0.5.0-py3-none-any.whl.metadata (849 bytes)
Requirement already satisfied: gensim<5.0.0,>=4.3.0 in /opt/conda/lib/python3.10/site-packages (from node2vec) (4.3.3)
Requirement already satisfied: joblib<2.0.0,>=1.4.0 in /opt/conda/lib/python3.10/site-packages (from node2vec) (1.4.2)
Requirement already satisfied: networkx<4.0.0,>=3.1.0 in /opt/conda/lib/python3.10/site-packages (from node2vec) (3.3)
Requirement already satisfied: numpy<2.0.0,>=1.24.0 in /opt/conda/lib/python3.10/site-packages (from node2vec) (1.26.4)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in /opt/conda/lib/python3.10/site-packages (from node2vec) (4.66.4)
Collecting scipy<1.14.0,>=1.7.0 (from gensim<5.0.0,>=4.3.0->node2vec)
  Downloading scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /opt/conda/lib/python3.10/site-packages (from gensim<5.0.0,>=4.3.0->node2vec) (7.0.4)
Requirement already satisfied: wrapt in /opt/conda/lib/python3.10/site-packages (from smart-open>=1.8.1->gensim<5.0.0,>=4.3.0->node2vec) (1.16.0)
Downloading node2vec-0.5.0-py3-none-any.whl (7.2 kB)
Downloading scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 38.9 MB/s eta 0:00:00:00:0100:01
Installing collected packages: scipy, node2vec
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.1
    Uninstalling scipy-1.14.1:
      Successfully uninstalled scipy-1.14.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cesium 0.12.3 requires numpy<3.0,>=2.0, but you have numpy 1.26.4 which is incompatible.
libpysal 4.9.2 requires packaging>=22, but you have packaging 21.3 which is incompatible.
libpysal 4.9.2 requires shapely>=2.0.1, but you have shapely 1.8.5.post1 which is incompatible.
tsfresh 0.20.3 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
Successfully installed node2vec-0.5.0 scipy-1.13.1

In [9]:
import networkx as nx
from node2vec import Node2Vec


# Initialize Node2Vec
node2vec = Node2Vec(G, dimensions=64, walk_length=30, num_walks=200, p=1, q=1, workers=4)

# Fit and transform the model
model = node2vec.fit(window=10, min_count=1, batch_words=4)

# Save model for future use
model.save("node2vec.model")

Generating walks (CPU: 2): 100%|██████████| 50/50 [00:00<00:00, 76.52it/s]
Generating walks (CPU: 1): 100%|██████████| 50/50 [00:00<00:00, 75.61it/s]
Generating walks (CPU: 3): 100%|██████████| 50/50 [00:00<00:00, 79.69it/s]
Generating walks (CPU: 4): 100%|██████████| 50/50 [00:00<00:00, 84.51it/s]

In [10]:
nodes_embedding = []
for i in range(len(df)):
    nodes_embedding.append(model.wv[list(G.nodes()).index(df.loc[i, "Concepts"].replace(" ", "_", -1))])

In [11]:
Concept_of_type_relation_embedding = []
for i in range(len(df)):
    Concept_of_type_relation_embedding.append(model.wv[list(G.nodes()).index(df.loc[i, "Concept_of_type_relation"].replace(" ", "_", -1))])

In [12]:
df['Nodes Embedding'] = nodes_embedding
df['Concept of Type Relation Embedding'] = Concept_of_type_relation_embedding

df.head()

,Concepts,Type_relation,Concept_of_type_relation,Definition,Synonym,Reference,Process_name,Figure,Nodes Embedding,Concept of Type Relation Embedding
0,plan risk management,studies,project risk,define the plan risk management concept. risk ...,NaN,"described in section 13.1.3.1,described in sec...",plan identify ambiguity,NaN,"[0.13667382, -0.38623685, 0.70960164, 0.218310...","[0.73298645, -0.15584536, 0.2066423, -0.348930..."
1,plan risk management,studies,project risk,define the plan risk management concept. the r...,NaN,"described in section 11.2.3.2,described in sec...",plan identify ambiguity,NaN,"[0.13667382, -0.38623685, 0.70960164, 0.218310...","[0.73298645, -0.15584536, 0.2066423, -0.348930..."
2,plan risk management inputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.37153205, -0.46170852, 0.3147171, 0.6941603...","[0.73298645, -0.15584536, 0.2066423, -0.348930..."
3,plan risk management tools and techniques,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.25836927, -0.21494018, -0.38267234, 0.28611...","[0.73298645, -0.15584536, 0.2066423, -0.348930..."
4,plan risk management outputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.30888477, -0.20805754, 0.18658443, 0.484829...","[0.73298645, -0.15584536, 0.2066423, -0.348930..."

In [13]:
from gensim.models import KeyedVectors

def get_edge_embedding(model, vec1, vec2, method='average'):
    
    if method == 'average':
        return (vec1 + vec2) / 2
    elif method == 'hadamard':
        return vec1 * vec2
    elif method == 'weighted_l1':
        return abs(vec1 - vec2)
    elif method == 'weighted_l2':
        return (vec1 - vec2) ** 2

In [14]:
edge_embedding = []
for i in range(len(df)):
    node1 = model.wv[list(G.nodes()).index(df.loc[i, "Concepts"].replace(" ", "_", -1))]
    node2 = model.wv[list(G.nodes()).index(df.loc[i, "Concept_of_type_relation"].replace(" ", "_", -1))]
    edge_embedding.append(get_edge_embedding(model, node1, node2, method='weighted_l2'))

In [15]:
df['Edge Embedding'] = edge_embedding
df.head()

,Concepts,Type_relation,Concept_of_type_relation,Definition,Synonym,Reference,Process_name,Figure,Nodes Embedding,Concept of Type Relation Embedding,Edge Embedding
0,plan risk management,studies,project risk,define the plan risk management concept. risk ...,NaN,"described in section 13.1.3.1,described in sec...",plan identify ambiguity,NaN,"[0.13667382, -0.38623685, 0.70960164, 0.218310...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.35558876, 0.05308024, 0.25296813, 0.3217625..."
1,plan risk management,studies,project risk,define the plan risk management concept. the r...,NaN,"described in section 11.2.3.2,described in sec...",plan identify ambiguity,NaN,"[0.13667382, -0.38623685, 0.70960164, 0.218310...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.35558876, 0.05308024, 0.25296813, 0.3217625..."
2,plan risk management inputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.37153205, -0.46170852, 0.3147171, 0.6941603...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.13064928, 0.09355226, 0.011680165, 1.088038..."
3,plan risk management tools and techniques,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.25836927, -0.21494018, -0.38267234, 0.28611...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.22526146, 0.0034921973, 0.34729174, 0.40328..."
4,plan risk management outputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.30888477, -0.20805754, 0.18658443, 0.484829...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.17986223, 0.0027261116, 0.00040231823, 0.69..."

In [16]:


from rdflib import Graph, URIRef, Literal, Namespace
import pandas as pd
import networkx as nx
import plotly.graph_objs as go


# Initialize an RDF graph
rdf_graph = Graph()
EX = Namespace("")

# Add data to RDF graph
for _, row in df.iterrows():
    subject = Literal(row['Nodes Embedding'])
    predicate = Literal(row['Edge Embedding'])
    obj = Literal(row['Concept of Type Relation Embedding'])
    rdf_graph.add((subject, predicate, obj))

In [17]:
df = df[df['Concepts'].notna()]
df = df[df['Concept_of_type_relation'].notna()]

In [18]:
G = nx.from_pandas_edgelist(df, 'Concepts', 'Concept_of_type_relation', edge_attr='Type_relation')

for _, row in df.iterrows():
    if row['Definition']:
        G.nodes[row['Concepts']]['x'] = (list(G.nodes()).index(row['Concepts']), row['Definition'])
    else:
        G.nodes[row['Concepts']]['x'] = (list(G.nodes()).index(row['Concepts']), "other")

    if row['Process_name']:
        G.nodes[row['Concept_of_type_relation']]['x'] = (list(G.nodes()).index(row['Concepts']), row['Definition'])
    else:
        G.nodes[row['Concept_of_type_relation']]['x'] = (list(G.nodes()).index(row['Concepts']), "other")

In [19]:
!pip install torch-geometric

Collecting torch-geometric
  Downloading torch_geometric-2.6.1-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from torch-geometric) (3.9.5)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch-geometric) (2024.6.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch-geometric) (3.1.4)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from torch-geometric) (1.26.4)
Requirement already satisfied: psutil>=5.8.0 in /opt/conda/lib/python3.10/site-packages (from torch-geometric) (5.9.3)
Requirement already satisfied: pyparsing in /opt/conda/lib/python3.10/site-packages (from torch-geometric) (3.1.2)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from torch-geometric) (2.32.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from torch-geometric) (4.66.4)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->torch-geometric) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->torch-geometric) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->torch-geometric) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->torch-geometric) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->torch-geometric) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->torch-geometric) (4.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch-geometric) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->torch-geometric) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->torch-geometric) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->torch-geometric) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->torch-geometric) (2024.8.30)
Downloading torch_geometric-2.6.1-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 16.3 MB/s eta 0:00:00a 0:00:01
Installing collected packages: torch-geometric
Successfully installed torch-geometric-2.6.1

In [20]:
!pip install sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-3.2.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (4.45.1)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (4.66.4)
Requirement already satisfied: torch>=1.11.0 in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (2.4.0+cpu)
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (0.25.1)
Requirement already satisfied: Pillow in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (10.3.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.15.1)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (21.3)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.5.15)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.20.0)
Requirement already satisfied: joblib>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.9->huggingface-hub>=0.20.0->sentence-transformers) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.8.30)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)
Downloading sentence_transformers-3.2.1-py3-none-any.whl (255 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.8/255.8 kB 3.7 MB/s eta 0:00:00 0:00:01
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-3.2.1

In [21]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Charger le modèle pré-entraîné
embb_model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
embb_model.eval()

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.73k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning:

`clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: BertModel
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
)

In [22]:
defention_embedding = []
for i in range(len(df)):
    defention_embedding.append(embb_model.encode(str(df.loc[i, "Definition"]), convert_to_tensor=False) )

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [23]:
Process_name_embedding = []
for i in range(len(df)):
    Process_name_embedding.append(embb_model.encode(str(df.loc[i, "Process_name"]), convert_to_tensor=False) )

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [25]:
df['Defention Embedding'] = defention_embedding
df['Process_name_embedding'] = Process_name_embedding

df.head()

,Concepts,Type_relation,Concept_of_type_relation,Definition,Synonym,Reference,Process_name,Figure,Nodes Embedding,Concept of Type Relation Embedding,Edge Embedding,Defention Embedding,Process_name_embedding
0,plan risk management,studies,project risk,define the plan risk management concept. risk ...,NaN,"described in section 13.1.3.1,described in sec...",plan identify ambiguity,NaN,"[0.13667382, -0.38623685, 0.70960164, 0.218310...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.35558876, 0.05308024, 0.25296813, 0.3217625...","[-0.20070007, 0.029315392, -0.16247118, -0.259...","[-0.47751307, 0.30824012, -0.37095937, -0.3750..."
1,plan risk management,studies,project risk,define the plan risk management concept. the r...,NaN,"described in section 11.2.3.2,described in sec...",plan identify ambiguity,NaN,"[0.13667382, -0.38623685, 0.70960164, 0.218310...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.35558876, 0.05308024, 0.25296813, 0.3217625...","[-0.3061132, 0.17728311, -0.018800333, -0.1801...","[-0.47751307, 0.30824012, -0.37095937, -0.3750..."
2,plan risk management inputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.37153205, -0.46170852, 0.3147171, 0.6941603...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.13064928, 0.09355226, 0.011680165, 1.088038...","[-0.46067682, 0.525866, -0.02412639, -0.413401...","[-0.47751307, 0.30824012, -0.37095937, -0.3750..."
3,plan risk management tools and techniques,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.25836927, -0.21494018, -0.38267234, 0.28611...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.22526146, 0.0034921973, 0.34729174, 0.40328...","[-0.46067682, 0.525866, -0.02412639, -0.413401...","[-0.47751307, 0.30824012, -0.37095937, -0.3750..."
4,plan risk management outputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.30888477, -0.20805754, 0.18658443, 0.484829...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.17986223, 0.0027261116, 0.00040231823, 0.69...","[-0.46067682, 0.525866, -0.02412639, -0.413401...","[-0.47751307, 0.30824012, -0.37095937, -0.3750..."

In [26]:
start_node = []
for _, row in df.iterrows():
    start_node.append(list(G.nodes()).index(row['Concepts']))
    
    
end_node = []
for _, row in df.iterrows():
    end_node.append(list(G.nodes()).index(row['Concept_of_type_relation']))
    
    
df['start_node'] = start_node
df['end_node'] = end_node

df.head()

,Concepts,Type_relation,Concept_of_type_relation,Definition,Synonym,Reference,Process_name,Figure,Nodes Embedding,Concept of Type Relation Embedding,Edge Embedding,Defention Embedding,Process_name_embedding,start_node,end_node
0,plan risk management,studies,project risk,define the plan risk management concept. risk ...,NaN,"described in section 13.1.3.1,described in sec...",plan identify ambiguity,NaN,"[0.13667382, -0.38623685, 0.70960164, 0.218310...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.35558876, 0.05308024, 0.25296813, 0.3217625...","[-0.20070007, 0.029315392, -0.16247118, -0.259...","[-0.47751307, 0.30824012, -0.37095937, -0.3750...",0,1
1,plan risk management,studies,project risk,define the plan risk management concept. the r...,NaN,"described in section 11.2.3.2,described in sec...",plan identify ambiguity,NaN,"[0.13667382, -0.38623685, 0.70960164, 0.218310...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.35558876, 0.05308024, 0.25296813, 0.3217625...","[-0.3061132, 0.17728311, -0.018800333, -0.1801...","[-0.47751307, 0.30824012, -0.37095937, -0.3750...",0,1
2,plan risk management inputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.37153205, -0.46170852, 0.3147171, 0.6941603...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.13064928, 0.09355226, 0.011680165, 1.088038...","[-0.46067682, 0.525866, -0.02412639, -0.413401...","[-0.47751307, 0.30824012, -0.37095937, -0.3750...",2,1
3,plan risk management tools and techniques,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.25836927, -0.21494018, -0.38267234, 0.28611...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.22526146, 0.0034921973, 0.34729174, 0.40328...","[-0.46067682, 0.525866, -0.02412639, -0.413401...","[-0.47751307, 0.30824012, -0.37095937, -0.3750...",3,1
4,plan risk management outputs,studies,project risk,NaN,NaN,NaN,plan identify ambiguity,NaN,"[0.30888477, -0.20805754, 0.18658443, 0.484829...","[0.73298645, -0.15584536, 0.2066423, -0.348930...","[0.17986223, 0.0027261116, 0.00040231823, 0.69...","[-0.46067682, 0.525866, -0.02412639, -0.413401...","[-0.47751307, 0.30824012, -0.37095937, -0.3750...",4,1

In [27]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([df['start_node'].values, df['end_node'].values] , dtype=torch.long)

# Edge features
edge_features = torch.tensor([list(i) for i in list(df['Edge Embedding'].values)], dtype=torch.float)

# If you also have node features in the DataFrame, define them
node_features = torch.tensor([list(i) for i in list(df['Defention Embedding'].values)], dtype=torch.float)

target = torch.tensor(df['end_node'].values, dtype=torch.long)


# Create the PyTorch Geometric data object
data = Data(x=node_features, edge_index=edge_index, edge_attr=edge_features, y=target )

/tmp/ipykernel_69/3642633147.py:4: UserWarning:

Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:278.)

In [39]:
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GNN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(GNN, self).__init__()
        self.conv1 = GCNConv(384, 384)
        self.conv2 = GCNConv(384, 153)
        

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        print(x)
       
        return x


from torch_geometric.loader import DataLoader

# Create a DataLoader if you have multiple graphs
# loader = DataLoader([data], batch_size=1, shuffle=True)

model = GNN(in_channels=1, hidden_channels=4, out_channels=2)  # Adjust channels as needed
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.CrossEntropyLoss()  # For classification tasks

# Training loop
model.train()
for epoch in range(200):  # Number of epochs
    optimizer.zero_grad()
    out = model(data)  # Forward pass
    loss = criterion(out, data.y)  # Compute loss
    loss.backward()  # Backward pass
    optimizer.step()  # Update weights

    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

tensor([[-6.8132e-02, -4.5486e-04,  1.7693e-01,  ..., -1.6148e-01,
         -1.8252e-01, -1.2755e-01],
        [-9.2444e-01,  6.3060e-01,  5.5805e-01,  ..., -1.3116e+00,
         -1.9172e+00, -8.6413e-01],
        [-3.0044e-01,  5.2068e-03, -1.2328e-01,  ..., -4.7552e-01,
          9.7467e-02, -1.1442e-01],
        ...,
        [-1.0984e-01,  6.0825e-02,  2.2461e-01,  ...,  1.4478e-01,
         -2.4925e-01,  3.2765e-02],
        [-6.5467e-02, -1.3367e-01,  9.1436e-02,  ..., -1.0011e-01,
         -2.7955e-01, -4.2282e-02],
        [-7.0415e-02,  1.1407e-01, -1.4438e-01,  ..., -2.3747e-01,
         -3.5910e-01, -1.8497e-01]], grad_fn=<AddBackward0>)
Epoch 1, Loss: 4.974666118621826
tensor([[ -0.9000,   4.3700,  -0.7824,  ...,  -1.1026,  -1.7384,  -1.3270],
        [-11.6822,  42.5906,  -7.5023,  ..., -10.9621, -13.5998, -10.7987],
        [ -2.4018,   6.7077,  -1.0718,  ...,  -2.0850,  -1.0985,  -1.1167],
        ...,
        [ -0.8702,   3.1332,  -0.3621,  ...,  -0.7115,  -1.3451,  -0.8471],
        [ -0.8837,   3.3458,  -0.5253,  ...,  -0.9414,  -1.4982,  -0.9059],
        [ -1.0845,   4.0264,  -0.7928,  ...,  -1.1974,  -1.7635,  -1.2256]],
       grad_fn=<AddBackward0>)
Epoch 2, Loss: 3.2479755878448486
tensor([[ -2.2844,   4.4120,  -1.7773,  ...,  -2.7611,  -3.3178,  -2.9815],
        [-25.5385,  45.0932, -18.1502,  ..., -26.0711, -27.4686, -24.7087],
        [ -4.6135,   7.5229,  -2.7880,  ...,  -4.1852,  -2.6174,  -2.5402],
        ...,
        [ -1.8356,   2.8880,  -1.0612,  ...,  -1.9242,  -2.3782,  -2.0306],
        [ -2.0397,   3.2690,  -1.4615,  ...,  -2.3408,  -2.7575,  -2.4152],
        [ -2.3210,   3.9665,  -1.7363,  ...,  -2.6689,  -3.1907,  -2.7239]],
       grad_fn=<AddBackward0>)
Epoch 3, Loss: 2.6994948387145996
tensor([[ -3.8159,   5.6419,  -3.4156,  ...,  -4.1310,  -5.1370,  -4.5295],
        [-39.5841,  57.4166, -32.5618,  ..., -38.8938, -43.4517, -38.1784],
        [ -6.6894,   9.4995,  -4.4834,  ...,  -6.0502,  -4.3464,  -4.2236],
        ...,
        [ -2.8066,   3.5674,  -2.1072,  ...,  -2.8807,  -3.5946,  -3.0538],
        [ -3.1845,   4.1228,  -2.7283,  ...,  -3.4262,  -4.2188,  -3.5725],
        [ -3.6293,   5.0449,  -3.1864,  ...,  -3.9550,  -4.8754,  -4.0714]],
       grad_fn=<AddBackward0>)
Epoch 4, Loss: 2.573821544647217
tensor([[ -5.1327,   7.3479,  -4.9184,  ...,  -5.3779,  -6.3661,  -5.9373],
        [-51.9130,  73.3487, -45.5183,  ..., -51.1026, -55.4338, -50.6532],
        [ -8.6090,  11.6198,  -6.1179,  ...,  -7.8315,  -6.1196,  -5.8890],
        ...,
        [ -3.5928,   4.5617,  -3.0015,  ...,  -3.7182,  -4.3323,  -3.9350],
        [ -4.1523,   5.2928,  -3.8179,  ...,  -4.4329,  -5.1284,  -4.5094],
        [ -4.6805,   6.5263,  -4.4433,  ...,  -5.1268,  -5.9696,  -5.2337]],
       grad_fn=<AddBackward0>)
Epoch 5, Loss: 2.4128544330596924
tensor([[ -6.2017,   7.6618,  -6.0225,  ...,  -6.3452,  -7.3492,  -7.0127],
        [-62.2367,  76.4521, -55.4805,  ..., -60.8661, -64.8417, -60.4600],
        [-10.1546,  11.9478,  -7.4905,  ...,  -9.3629,  -7.4542,  -7.1964],
        ...,
        [ -4.2406,   4.4755,  -3.5900,  ...,  -4.2552,  -4.8298,  -4.5045],
        [ -4.9572,   5.2849,  -4.5213,  ...,  -5.2441,  -5.7888,  -5.2338],
        [ -5.5984,   6.6878,  -5.3170,  ...,  -6.0824,  -6.8379,  -6.1077]],
       grad_fn=<AddBackward0>)
Epoch 6, Loss: 2.1775197982788086
tensor([[ -7.1636,   7.3822,  -6.9272,  ...,  -7.2143,  -8.2074,  -7.9598],
        [-71.6050,  74.7521, -64.2624,  ..., -69.4376, -73.2350, -69.2787],
        [-11.5153,  11.8342,  -8.8205,  ..., -10.7356,  -8.6314,  -8.4176],
        ...,
        [ -4.8597,   3.9609,  -4.0297,  ...,  -4.7162,  -5.2517,  -4.9534],
        [ -5.6607,   4.8097,  -5.0281,  ...,  -5.9903,  -6.3241,  -5.8787],
        [ -6.4994,   6.3145,  -6.0685,  ...,  -6.9576,  -7.6152,  -6.9695]],
       grad_fn=<AddBackward0>)
Epoch 7, Loss: 1.9553977251052856
tensor([[ -8.1160,   7.6424,  -7.9066,  ...,  -8.0445,  -9.0715,  -9.0073],
        [-80.8092,  77.8356, -73.8066,  ..., -77.7408, -81.7906, -78.8533],
        [-12.7590,  12.4167, -10.1536,  ..., -12.0299,  -9.7393,  -9.6196],
        ...,
        [ -5.3758,   3.8193,  -4.5172,  ...,  -5.1249,  -5.6564,  -5.4493],
        [ -6.3613,   4.7369,  -5.6683,  ...,  -6.6471,  -6.9572,  -6.6543],
        [ -7.3735,   6.4218,  -6.9465,  ...,  -7.8023,  -8.4438,  -7.9366]],
       grad_fn=<AddBackward0>)
Epoch 8, Loss: 1.8344323635101318
tensor([[ -9.0349,   8.4874,  -9.0113,  ...,  -8.7781, -10.0421, -10.0480],
        [-89.6943,  85.8642, -84.0186,  ..., -85.2727, -90.9968, -88.4068],
        [-13.9420,  13.5154, -11.3906,  ..., -13.2255, -10.8622, -10.8139],
        ...,
        [ -5.8247,   4.1325,  -5.0780,  ...,  -5.4091,  -6.1475,  -5.9086],
        [ -6.9460,   5.1708,  -6.3867,  ...,  -7.1359,  -7.5925,  -7.3332],
        [ -8.1684,   7.0953,  -7.9229,  ...,  -8.5056,  -9.2983,  -8.8555]],
       grad_fn=<AddBackward0>)
Epoch 9, Loss: 1.683929681777954
tensor([[ -9.9604,   9.0669, -10.1028,  ...,  -9.5279, -11.0099, -11.0497],
        [-98.2642,  91.5722, -93.6281,  ..., -92.6697, -99.7499, -97.3971],
        [-15.0393,  14.2651, -12.5151,  ..., -14.3099, -11.9005, -11.8856],
        ...,
        [ -6.2726,   4.3432,  -5.6321,  ...,  -5.7124,  -6.6438,  -6.3386],
        [ -7.5160,   5.4823,  -7.0671,  ...,  -7.6120,  -8.1656,  -7.9396],
        [ -8.9239,   7.6118,  -8.8486,  ...,  -9.1735, -10.0761,  -9.7168]],
       grad_fn=<AddBackward0>)
Epoch 10, Loss: 1.5877115726470947
tensor([[ -10.8421,    9.1956,  -11.0945,  ...,  -10.2983,  -11.8765,
          -12.0124],
        [-106.1376,   93.3033, -102.2244,  ..., -100.0161, -107.6443,
         -105.7220],
        [ -15.9899,   14.4140,  -13.5176,  ...,  -15.2617,  -12.7963,
          -12.7943],
        ...,
        [  -6.7027,    4.3070,   -6.1126,  ...,   -6.0853,   -7.0834,
           -6.7860],
        [  -8.0829,    5.5411,   -7.6600,  ...,   -8.1298,   -8.6738,
           -8.5155],
        [  -9.6425,    7.8252,   -9.6952,  ...,   -9.9025,  -10.7865,
          -10.5457]], grad_fn=<AddBackward0>)
Epoch 11, Loss: 1.4662991762161255
tensor([[ -11.7228,    9.3098,  -12.0663,  ...,  -11.1672,  -12.7659,
          -12.9584],
        [-114.0321,   95.0122, -110.4973,  ..., -107.7450, -115.6106,
         -113.7621],
        [ -16.8847,   14.6073,  -14.4391,  ...,  -16.1378,  -13.6724,
          -13.6578],
        ...,
        [  -7.1826,    4.2429,   -6.5803,  ...,   -6.5647,   -7.5791,
           -7.2405],
        [  -8.7547,    5.6078,   -8.2444,  ...,   -8.7462,   -9.2440,
           -9.0995],
        [ -10.4299,    8.0372,  -10.5050,  ...,  -10.7188,  -11.5571,
          -11.3782]], grad_fn=<AddBackward0>)
Epoch 12, Loss: 1.3903664350509644
tensor([[ -12.5683,    9.9570,  -13.0059,  ...,  -12.0873,  -13.6685,
          -13.8366],
        [-121.8108,  100.8633, -118.6446,  ..., -115.5677, -123.7070,
         -121.5328],
        [ -17.7438,   15.3128,  -15.2833,  ...,  -16.9470,  -14.5666,
          -14.5349],
        ...,
        [  -7.6763,    4.4625,   -7.0745,  ...,   -7.0814,   -8.0924,
           -7.6998],
        [  -9.4948,    5.9432,   -8.8932,  ...,   -9.4485,   -9.8935,
           -9.7461],
        [ -11.2587,    8.5637,  -11.3196,  ...,  -11.5726,  -12.3679,
          -12.2145]], grad_fn=<AddBackward0>)
Epoch 13, Loss: 1.2578866481781006
tensor([[ -13.3975,   10.5728,  -13.8717,  ...,  -12.9379,  -14.5563,
          -14.6412],
        [-129.1407,  105.1395, -126.0442,  ..., -122.7441, -131.3342,
         -128.5317],
        [ -18.4880,   15.4973,  -16.0250,  ...,  -17.6420,  -15.2872,
          -15.2187],
        ...,
        [  -8.1679,    4.6330,   -7.5349,  ...,   -7.5715,   -8.6095,
           -8.1494],
        [ -10.2003,    6.1335,   -9.4919,  ...,  -10.0968,  -10.5748,
          -10.3514],
        [ -12.0459,    8.9391,  -12.0668,  ...,  -12.3644,  -13.1830,
          -12.9807]], grad_fn=<AddBackward0>)
Epoch 14, Loss: 1.1747565269470215
tensor([[ -14.1314,   10.7922,  -14.5955,  ...,  -13.6412,  -15.3794,
          -15.3349],
        [-135.4986,  105.1333, -132.2127,  ..., -128.7207, -137.8265,
         -134.3974],
        [ -19.1070,   14.9640,  -16.6418,  ...,  -18.1774,  -15.7869,
          -15.6714],
        ...,
        [  -8.5756,    4.5265,   -7.9214,  ...,   -7.9668,   -9.0805,
           -8.5565],
        [ -10.7950,    5.9676,   -9.9804,  ...,  -10.6021,  -11.1637,
          -10.8757],
        [ -12.7048,    8.9119,  -12.6855,  ...,  -13.0047,  -13.8839,
          -13.6280]], grad_fn=<AddBackward0>)
Epoch 15, Loss: 1.0832362174987793
tensor([[ -14.8116,   11.0108,  -15.2640,  ...,  -14.2681,  -16.1230,
          -15.9956],
        [-141.2875,  105.3582, -137.9852,  ..., -134.1883, -143.6975,
         -139.9413],
        [ -19.6694,   14.5396,  -17.2060,  ...,  -18.6719,  -16.2110,
          -16.0792],
        ...,
        [  -8.9112,    4.4355,   -8.2932,  ...,   -8.2980,   -9.5036,
           -8.9313],
        [ -11.3176,    5.8179,  -10.4302,  ...,  -11.0299,  -11.6566,
          -11.3504],
        [ -13.2983,    8.9169,  -13.2595,  ...,  -13.5954,  -14.5095,
          -14.2413]], grad_fn=<AddBackward0>)
Epoch 16, Loss: 1.0182372331619263
tensor([[ -15.4884,   11.7066,  -16.0217,  ...,  -14.9483,  -16.8541,
          -16.7182],
        [-147.0769,  110.5149, -144.2084,  ..., -139.9962, -149.6701,
         -145.9917],
        [ -20.2532,   14.9701,  -17.7759,  ...,  -19.2058,  -16.7231,
          -16.6141],
        ...,
        [  -9.2228,    4.6658,   -8.7023,  ...,   -8.6306,   -9.8869,
           -9.3281],
        [ -11.8053,    6.0746,  -10.9054,  ...,  -11.4890,  -12.1214,
          -11.8426],
        [ -13.9046,    9.3965,  -13.8888,  ...,  -14.2294,  -15.1221,
          -14.8897]], grad_fn=<AddBackward0>)
Epoch 17, Loss: 0.9264886379241943
tensor([[ -16.1370,   12.3174,  -16.7682,  ...,  -15.6261,  -17.5202,
          -17.3946],
        [-152.6817,  115.9329, -150.3312,  ..., -145.7478, -155.3149,
         -151.7476],
        [ -20.8330,   15.7372,  -18.3506,  ...,  -19.7475,  -17.2717,
          -17.1917],
        ...,
        [  -9.5243,    4.8770,   -9.1026,  ...,   -8.9576,  -10.2325,
           -9.6850],
        [ -12.2608,    6.3648,  -11.3852,  ...,  -11.9722,  -12.5528,
          -12.3183],
        [ -14.5129,    9.9016,  -14.5323,  ...,  -14.8909,  -15.7111,
          -15.5046]], grad_fn=<AddBackward0>)
Epoch 18, Loss: 0.8577889204025269
tensor([[ -16.6982,   12.3518,  -17.3807,  ...,  -16.1523,  -18.0547,
          -17.9395],
        [-157.6669,  116.9696, -155.4602,  ..., -150.5282, -160.0109,
         -156.4010],
        [ -21.3619,   16.1091,  -18.8594,  ...,  -20.2391,  -17.7522,
          -17.6772],
        ...,
        [  -9.8129,    4.7790,   -9.4621,  ...,   -9.2432,  -10.5403,
           -9.9774],
        [ -12.6862,    6.3260,  -11.7798,  ...,  -12.4015,  -12.9302,
          -12.6926],
        [ -15.0574,    9.9872,  -15.0659,  ...,  -15.4280,  -16.1932,
          -15.9876]], grad_fn=<AddBackward0>)
Epoch 19, Loss: 0.788104236125946
tensor([[ -17.2553,   12.3826,  -17.9491,  ...,  -16.6225,  -18.5739,
          -18.4563],
        [-162.4667,  117.3359, -160.1431,  ..., -154.8047, -164.4877,
         -160.7062],
        [ -21.8329,   16.2270,  -19.3053,  ...,  -20.6858,  -18.1769,
          -18.0932],
        ...,
        [ -10.1231,    4.6709,   -9.7990,  ...,   -9.5092,  -10.8495,
          -10.2632],
        [ -13.1285,    6.2416,  -12.1601,  ...,  -12.8109,  -13.3245,
          -13.0534],
        [ -15.5855,   10.0073,  -15.5421,  ...,  -15.8874,  -16.6627,
          -16.4306]], grad_fn=<AddBackward0>)
Epoch 20, Loss: 0.7452316284179688
tensor([[ -17.8563,   12.9967,  -18.5554,  ...,  -17.1377,  -19.1603,
          -19.0287],
        [-167.3719,  121.5568, -164.9875,  ..., -159.1701, -169.2812,
         -165.2838],
        [ -22.2748,   16.4674,  -19.7195,  ...,  -21.1097,  -18.6004,
          -18.4940],
        ...,
        [ -10.4546,    4.8800,  -10.1335,  ...,   -9.7993,  -11.1661,
          -10.5890],
        [ -13.5954,    6.4653,  -12.6119,  ...,  -13.2452,  -13.7706,
          -13.4795],
        [ -16.1185,   10.4045,  -16.0291,  ...,  -16.3598,  -17.1719,
          -16.9124]], grad_fn=<AddBackward0>)
Epoch 21, Loss: 0.672497034072876
tensor([[ -18.4213,   13.6267,  -19.1140,  ...,  -17.6687,  -19.7251,
          -19.5963],
        [-171.8645,  124.9759, -169.3287,  ..., -163.4453, -173.7346,
         -169.6623],
        [ -22.6650,   16.3615,  -20.0531,  ...,  -21.4977,  -18.9544,
          -18.8038],
        ...,
        [ -10.7580,    5.0606,  -10.4349,  ...,  -10.0944,  -11.4497,
          -10.9223],
        [ -14.0329,    6.6433,  -13.0249,  ...,  -13.6855,  -14.1939,
          -13.9031],
        [ -16.6011,   10.7394,  -16.4643,  ...,  -16.8332,  -17.6565,
          -17.3961]], grad_fn=<AddBackward0>)
Epoch 22, Loss: 0.626768946647644
tensor([[ -18.8602,   13.7066,  -19.5470,  ...,  -18.1091,  -20.1516,
          -20.0763],
        [-175.4953,  123.9110, -172.6647,  ..., -167.0908, -177.1922,
         -173.2574],
        [ -23.0040,   15.7796,  -20.3000,  ...,  -21.8231,  -19.2211,
          -19.0103],
        ...,
        [ -10.9932,    4.9167,  -10.6617,  ...,  -10.3364,  -11.6598,
          -11.1966],
        [ -14.3847,    6.4625,  -13.3209,  ...,  -14.0502,  -14.5130,
          -14.2507],
        [ -16.9901,   10.6486,  -16.8053,  ...,  -17.2520,  -18.0425,
          -17.8119]], grad_fn=<AddBackward0>)
Epoch 23, Loss: 0.581864595413208
tensor([[ -19.2801,   13.9604,  -19.9904,  ...,  -18.5454,  -20.5561,
          -20.5068],
        [-179.0147,  125.1887, -176.2282,  ..., -170.6470, -180.7140,
         -176.8211],
        [ -23.3521,   15.7205,  -20.5807,  ...,  -22.1014,  -19.5418,
          -19.3083],
        ...,
        [ -11.2034,    4.9061,  -10.9071,  ...,  -10.5726,  -11.8642,
          -11.4516],
        [ -14.7051,    6.4669,  -13.6436,  ...,  -14.4162,  -14.8214,
          -14.5891],
        [ -17.3743,   10.7526,  -17.1722,  ...,  -17.6794,  -18.4286,
          -18.2046]], grad_fn=<AddBackward0>)
Epoch 24, Loss: 0.5410614609718323
tensor([[ -19.7151,   14.4968,  -20.4675,  ...,  -18.9919,  -20.9847,
          -20.9204],
        [-182.6983,  129.8139, -180.2466,  ..., -174.2769, -184.4951,
         -180.4970],
        [ -23.7431,   16.3170,  -20.9450,  ...,  -22.4206,  -19.9198,
          -19.7038],
        ...,
        [ -11.4098,    5.0860,  -11.1769,  ...,  -10.8019,  -12.0715,
          -11.6959],
        [ -15.0131,    6.7204,  -13.9759,  ...,  -14.7616,  -15.1151,
          -14.8935],
        [ -17.7757,   11.1538,  -17.5778,  ...,  -18.1021,  -18.8275,
          -18.5819]], grad_fn=<AddBackward0>)
Epoch 25, Loss: 0.5052754282951355
tensor([[ -20.0796,   14.5609,  -20.8559,  ...,  -19.3413,  -21.3502,
          -21.2708],
        [-185.8821,  130.7047, -183.4262,  ..., -177.2354, -187.5056,
         -183.5180],
        [ -24.0815,   16.5462,  -21.2105,  ...,  -22.6821,  -20.2052,
          -19.9992],
        ...,
        [ -11.5894,    5.0127,  -11.4157,  ...,  -10.9988,  -12.2464,
          -11.9109],
        [ -15.2832,    6.6888,  -14.2257,  ...,  -15.0479,  -15.3385,
          -15.1461],
        [ -18.1119,   11.2165,  -17.8884,  ...,  -18.4219,  -19.1199,
          -18.8884]], grad_fn=<AddBackward0>)
Epoch 26, Loss: 0.47016534209251404
tensor([[ -20.4542,   14.7121,  -21.2396,  ...,  -19.6937,  -21.7304,
          -21.6284],
        [-188.9250,  131.8011, -186.4552,  ..., -180.1147, -190.4458,
         -186.5109],
        [ -24.3321,   16.6237,  -21.4108,  ...,  -22.9195,  -20.4218,
          -20.2494],
        ...,
        [ -11.8007,    5.0008,  -11.6766,  ...,  -11.2258,  -12.4451,
          -12.1617],
        [ -15.5697,    6.6880,  -14.4799,  ...,  -15.3327,  -15.5622,
          -15.4172],
        [ -18.4474,   11.3227,  -18.1929,  ...,  -18.7181,  -19.4058,
          -19.1954]], grad_fn=<AddBackward0>)
Epoch 27, Loss: 0.4451061487197876
tensor([[ -20.8534,   15.2532,  -21.6453,  ...,  -20.0737,  -22.1223,
          -21.9956],
        [-192.0233,  135.7469, -189.7694,  ..., -183.1868, -193.6163,
         -189.7445],
        [ -24.5428,   16.8256,  -21.6308,  ...,  -23.1831,  -20.6512,
          -20.5472],
        ...,
        [ -12.0523,    5.2288,  -11.9612,  ...,  -11.4764,  -12.6827,
          -12.4413],
        [ -15.8811,    6.9090,  -14.7805,  ...,  -15.6267,  -15.8208,
          -15.7272],
        [ -18.8083,   11.7084,  -18.5456,  ...,  -19.0501,  -19.7384,
          -19.5328]], grad_fn=<AddBackward0>)
Epoch 28, Loss: 0.41275137662887573
tensor([[ -21.2085,   15.5031,  -21.9863,  ...,  -20.3970,  -22.4743,
          -22.3129],
        [-194.7249,  136.8300, -192.4505,  ..., -185.7401, -196.2954,
         -192.4008],
        [ -24.7077,   16.6156,  -21.7812,  ...,  -23.3936,  -20.8141,
          -20.7715],
        ...,
        [ -12.2879,    5.2598,  -12.1847,  ...,  -11.6842,  -12.8916,
          -12.6655],
        [ -16.1489,    6.8932,  -15.0255,  ...,  -15.8667,  -16.0511,
          -16.0049],
        [ -19.1212,   11.8213,  -18.8408,  ...,  -19.3427,  -20.0314,
          -19.8318]], grad_fn=<AddBackward0>)
Epoch 29, Loss: 0.3906398415565491
tensor([[ -21.4830,   15.3919,  -22.2316,  ...,  -20.6379,  -22.7511,
          -22.5596],
        [-196.9537,  135.2790, -194.4439,  ..., -187.7420, -198.4003,
         -194.4902],
        [ -24.8826,   16.2963,  -21.9189,  ...,  -23.5720,  -20.9688,
          -20.9624],
        ...,
        [ -12.4758,    5.0550,  -12.3296,  ...,  -11.8348,  -13.0450,
          -12.8205],
        [ -16.3474,    6.6088,  -15.1882,  ...,  -16.0336,  -16.2229,
          -16.2201],
        [ -19.3629,   11.6387,  -19.0597,  ...,  -19.5779,  -20.2620,
          -20.0789]], grad_fn=<AddBackward0>)
Epoch 30, Loss: 0.373207151889801
tensor([[ -21.7370,   15.6203,  -22.4846,  ...,  -20.9014,  -23.0041,
          -22.8086],
        [-199.1868,  137.4743, -196.7823,  ..., -189.9363, -200.6629,
         -196.8710],
        [ -25.1235,   16.6553,  -22.1522,  ...,  -23.7796,  -21.2227,
          -21.2376],
        ...,
        [ -12.6351,    5.0697,  -12.4816,  ...,  -11.9833,  -13.1866,
          -12.9803],
        [ -16.5166,    6.5951,  -15.3721,  ...,  -16.1980,  -16.3992,
          -16.4428],
        [ -19.5888,   11.7617,  -19.3004,  ...,  -19.8300,  -20.4975,
          -20.3365]], grad_fn=<AddBackward0>)
Epoch 31, Loss: 0.3481888175010681
tensor([[ -21.9743,   15.8182,  -22.7318,  ...,  -21.1750,  -23.2415,
          -23.0778],
        [-201.2763,  139.4403, -199.0571,  ..., -192.1243, -202.7552,
         -199.2942],
        [ -25.3603,   16.9851,  -22.3764,  ...,  -23.9536,  -21.4478,
          -21.4756],
        ...,
        [ -12.7684,    5.0897,  -12.6387,  ...,  -12.1310,  -13.3154,
          -13.1513],
        [ -16.6653,    6.6030,  -15.5374,  ...,  -16.3574,  -16.5606,
          -16.6582],
        [ -19.7934,   11.8792,  -19.5328,  ...,  -20.0941,  -20.7123,
          -20.6059]], grad_fn=<AddBackward0>)
Epoch 32, Loss: 0.33105817437171936
tensor([[ -22.2086,   15.8538,  -22.9726,  ...,  -21.4403,  -23.4836,
          -23.3493],
        [-203.2483,  139.4304, -201.1264,  ..., -194.1710, -204.6693,
         -201.5354],
        [ -25.5427,   16.8892,  -22.5297,  ...,  -24.0660,  -21.5805,
          -21.6211],
        ...,
        [ -12.9090,    5.0305,  -12.8097,  ...,  -12.2896,  -13.4567,
          -13.3334],
        [ -16.8080,    6.5033,  -15.6861,  ...,  -16.5136,  -16.7173,
          -16.8637],
        [ -19.9895,   11.8517,  -19.7502,  ...,  -20.3570,  -20.9156,
          -20.8757]], grad_fn=<AddBackward0>)
Epoch 33, Loss: 0.3162098824977875
tensor([[ -22.4989,   16.1749,  -23.2639,  ...,  -21.7350,  -23.7866,
          -23.6323],
        [-205.4866,  141.4976, -203.5608,  ..., -196.3617, -206.9617,
         -203.8488],
        [ -25.7057,   16.8673,  -22.6923,  ...,  -24.1867,  -21.7046,